version: '2'
services:
  geoserver:
    image: quay.io/geomesa/geoserver:geomesa-2.2.1-accumulo-1.9.2
    ports:
      - 9090:9090
  hdfs-name:
    image: quay.io/geomesa/hdfs:geomesa-2.2.1-accumulo-1.9.2
    command: name
    environment:
      HADOOP_MASTER_ADDRESS: hdfs-name
    ports:
      - 50070:50070
  hdfs-data:
    image: quay.io/geomesa/hdfs:geomesa-2.2.1-accumulo-1.9.2
    command: data
    environment:
      HADOOP_MASTER_ADDRESS: hdfs-name
    depends_on:
      - hdfs-name
  zookeeper:
    image: quay.io/geomesa/zookeeper:latest
    ports:
      - 2181:2181
  accumulo-master:
    image: quay.io/geomesa/accumulo-geomesa:geomesa-2.2.1-accumulo-1.9.2
    command: master --auto-init
    environment:
      HADOOP_MASTER_ADDRESS: hdfs-name
      ZOOKEEPERS: zookeeper
      ACCUMULO_PASSWORD: GisPwd
    depends_on:
      - zookeeper
  accumulo-monitor:
    image: quay.io/geomesa/accumulo-geomesa:geomesa-2.2.1-accumulo-1.9.2
    command: monitor
    environment:
      HADOOP_MASTER_ADDRESS: hdfs-name
      ZOOKEEPERS: zookeeper
    ports:
      - 9995:9995
      - 50095:50095
    depends_on:
      - zookeeper
      - accumulo-master
  accumulo-tserver:
    image: quay.io/geomesa/accumulo-geomesa:geomesa-2.2.1-accumulo-1.9.2
    command: tserver
    environment:
      HADOOP_MASTER_ADDRESS: hdfs-name
      ZOOKEEPERS: zookeeper
    depends_on:
      - zookeeper
      - accumulo-master
  kafka:
    image: wurstmeister/kafka
    hostname: kafka
    ports:
      - "9092:9092"
    expose:
      - "9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock